production:
  deny_delete: true
  auto_create: false
  force_repository: true
  pre_create: /usr/local/bin/pre-create.sh
  post_create: /usr/local/bin/post-create.sh
  pre_delete: /usr/local/bin/pre-delete.sh
  post_delete: /usr/local/bin/post-delete.sh
  max_repos: 0
  only_creator: false
  svn:
    path: /var/scm_repo/svn
    svn: /usr/bin/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
  git:
    path: /var/scm_repo/git
    git: /usr/bin/git
    options: --bare
    url: http://zyac-open.chinacloudapp.cn:3000
    update_server_info: true
    git_ext: true
    append: trunk
  mercurial:
    path: /var/lib/mercurial
    hg: /usr/bin/hg
  bazaar:
    path: /var/lib/bazaar
    bzr: /usr/bin/bzr
    init: init-repository
    log_encoding: UTF-8
  gitlab:
    path: /var/scm_repo/gitlab
    options: --mirror
    url: http://zyac-open.chinacloudapp.cn:8888
    append: .git

development:
  deny_delete: true
  auto_create: false
  force_repository: true
  pre_create: /usr/local/bin/pre-create.sh
  post_create: /usr/local/bin/post-create.sh
  pre_delete: /usr/local/bin/pre-delete.sh
  post_delete: /usr/local/bin/post-delete.sh
  max_repos: 0
  only_creator: false
  svn:
    path: /var/scm_repo/svn
    svn: /usr/bin/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
  git:
    path: /var/scm_repo/git
    git: /usr/bin/git
    options: --bare
    url: http://zyac-open.chinacloudapp.cn:3000
    update_server_info: true
    git_ext: true
    append: trunk
  mercurial:
    path: /var/lib/mercurial
    hg: /usr/bin/hg
  bazaar:
    path: /var/lib/bazaar
    bzr: /usr/bin/bzr
    init: init-repository
    log_encoding: UTF-8
  gitlab:
    path: /var/scm_repo/gitlab
    options: --mirror
    url: http://zyac-open.chinacloudapp.cn:8888
    append: .git
